const cfg=window.DNH_CONFIG||{};
const sb=window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey);
let profile=null,settings={name:'DNH BARBEARIA',whatsapp:'',start_time:'08:00',end_time:'18:00',slot_interval:30,logo_url:'dnh-logo.png'},services=[],professionals=[];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const today=()=>{const d=new Date();return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)};
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const digits=v=>(v||'').replace(/\D/g,'');
const ADMIN_PAGES=['dashboard','services','clients','stock','finance','team','settings'];
const CLIENT_PAGES=['agenda','consultar'];
const isAdmin=()=>profile?.role==='admin',isClient=()=>profile?.role==='client';
const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');
const fmtDate=d=>d?`${d.slice(8,10)}/${d.slice(5,7)}/${d.slice(0,4)}`:'';
const serviceName=id=>services.find(x=>String(x.id)===String(id))?.name||'Serviço';
const profName=id=>professionals.find(x=>String(x.id)===String(id))?.name||'Profissional';
const duration=id=>Number(services.find(x=>String(x.id)===String(id))?.duration||30);
const timeMin=t=>{const [h,m]=String(t).slice(0,5).split(':').map(Number);return h*60+m};
function slots(){let [h,m]=String(settings.start_time||'08:00').slice(0,5).split(':').map(Number),[eh,em]=String(settings.end_time||'18:00').slice(0,5).split(':').map(Number),cur=h*60+m,end=eh*60+em,int=Number(settings.slot_interval)||30,r=[];while(cur<end){r.push(`${String(Math.floor(cur/60)).padStart(2,'0')}:${String(cur%60).padStart(2,'0')}`);cur+=int}return r}
function canAccessPage(p){return !!profile&&(isAdmin()?true:CLIENT_PAGES.includes(p))}
function aplicarPermissoesUI(){const admin=isAdmin();$$('.admin-only').forEach(e=>e.classList.toggle('hidden',!admin));$$('[data-page]').forEach(e=>{if(ADMIN_PAGES.includes(e.dataset.page))e.classList.toggle('hidden',!admin)});$('#clientAgenda')?.classList.toggle('hidden',admin);$('#adminAgenda')?.classList.toggle('hidden',!admin)}
	async function user(){const {data:a,error:ae}=await sb.auth.getUser();if(ae||!a?.user){profile=null;return null}const {data,error}=await sb.from('profiles').select('*').eq('id',a.user.id).maybeSingle();if(error){console.error('ERRO PERFIL:',error);profile=null;return null}profile=data||{id:a.user.id,email:a.user.email,role:'client'};return profile}
	async function loadSettings(){const {data,error}=await sb.from('settings').select('*').limit(1).maybeSingle();if(error)console.warn('CONFIG:',error);if(data)settings={...settings,...data};if($('#brandName'))$('#brandName').textContent=settings.name||'DNH BARBEARIA';if($('#roleLabel'))$('#roleLabel').textContent=isAdmin()?'Administrador':'Cliente';if($('#brandLogo')&&settings.logo_url)$('#brandLogo').src=settings.logo_url}
	async function loadServices(){const {data,error}=await sb.from('services').select('*').order('name');if(error){console.error('SERVIÇOS:',error);services=[];return}services=data||[];const s=$('#clientService');if(s){const old=s.value;s.innerHTML='<option value="">Selecione um serviço</option>';services.filter(x=>x.active!==false).forEach(x=>{const o=document.createElement('option');o.value=x.id;o.textContent=`${x.name} — ${money(x.price)} (${x.duration||30} min)`;s.appendChild(o)});s.value=old}renderServices()}
	async function loadProfessionals(){const {data,error}=await sb.from('professionals').select('*').order('name');if(error){console.error('PROFISSIONAIS:',error);professionals=[];return}professionals=data||[];for(const [id,first] of [['clientProfessional','Selecione um profissional'],['agendaProfessional','Todos os profissionais']]){const s=$(`#${id}`);if(!s)continue;const old=s.value;s.innerHTML=`<option value="">${first}</option>`;professionals.filter(x=>x.active!==false).forEach(x=>{const o=document.createElement('option');o.value=x.id;o.textContent=x.name;s.appendChild(o)});s.value=old}renderTeam()}
	async function go(page){if(!profile)return;if(!canAccessPage(page))page=isAdmin()?'dashboard':'agenda';$$('.page').forEach(x=>x.classList.remove('active'));$(`#page-${page}`)?.classList.add('active');$$('[data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page===page));if(page==='dashboard'&&isAdmin())await dashboard();if(page==='agenda')await agenda();if(page==='consultar'&&isClient())await consultarAgenda();if(page==='services'&&isAdmin())await loadServices();if(page==='clients'&&isAdmin())await loadClients();if(page==='stock'&&isAdmin())await loadStock();if(page==='finance'&&isAdmin())await loadFinance();if(page==='team'&&isAdmin())await loadProfessionals();if(page==='settings'&&isAdmin())await loadSettingsPage()}
	async function dashboard(){if(!isAdmin())return;await loadSettings();const month=today().slice(0,7);const [{data:b,error:be},{count,error:ce},{data:c,error:ee},{data:p,error:pe}]=await Promise.all([sb.from('bookings').select('*').eq('date',today()).neq('status','cancelled').order('time'),sb.from('profiles').select('id',{count:'exact',head:true}).eq('role','client'),sb.from('cash_entries').select('*').gte('date',`${month}-01`).lte('date',`${month}-31`),sb.from('profiles').select('id,name,birth,phone,email').eq('role','client')]);if(be)console.error('DASH AGENDA:',be);if(ce)console.error('DASH CLIENTES:',ce);if(ee)console.error('DASH FINANCEIRO:',ee);if(pe)console.error('DASH ANIVERSÁRIOS:',pe);const bookings=b||[],cash=c||[],clients=p||[];const revenue=cash.filter(x=>x.type==='income').reduce((a,x)=>a+Number(x.amount||0),0);const birthdays=clients.filter(x=>x.birth&&String(x.birth).slice(5,7)===month.slice(5,7)).sort((a,z)=>String(a.birth).slice(8,10).localeCompare(String(z.birth).slice(8,10)));if($('#kToday'))$('#kToday').textContent=bookings.length;if($('#kClients'))$('#kClients').textContent=count||0;if($('#kRevenue'))$('#kRevenue').textContent=money(revenue);if($('#kBirthdays'))$('#kBirthdays').textContent=birthdays.length;if($('#todayList'))$('#todayList').innerHTML=bookings.length?bookings.map(x=>`<div class="list-row"><div><b>${esc(x.time)}</b><small>${esc(serviceName(x.service_id))}</small></div><span>${esc(profName(x.professional_id))}</span></div>`).join(''):'<p class="muted">Nenhum agendamento hoje.</p>';if($('#birthdayList'))$('#birthdayList').innerHTML=birthdays.slice(0,6).map(x=>`<div class="list-row"><div><b>🎂 ${esc(x.name||'Cliente')}</b><small>${x.birth.slice(8,10)}/${x.birth.slice(5,7)} • ${esc(x.phone||'')}</small></div><span>${x.birth.slice(8,10)===today().slice(8,10)?'Hoje':''}</span></div>`).join('')||'<p class="muted">Nenhum aniversariante este mês.</p>'}
	async function agenda(){if(!profile)return;if(isAdmin()){$('#clientAgenda')?.classList.add('hidden');$('#adminAgenda')?.classList.remove('hidden');await loadSettings();await loadProfessionals();await agendaAdmin();return}if(isClient()){$('#clientAgenda')?.classList.remove('hidden');$('#adminAgenda')?.classList.add('hidden');await loadSettings();await loadServices();await loadProfessionals();initClientBooking();await loadClientTimes()}}
	async function agendaAdmin(){if(!isAdmin())return;const date=$('#agendaDate'),grid=$('#agendaGrid');if(!date||!grid)return;if(!date.value)date.value=today();let q=sb.from('bookings').select('*').eq('date',date.value).neq('status','cancelled').order('time');if($('#agendaProfessional')?.value)q=q.eq('professional_id',$('#agendaProfessional').value);const {data,error}=await q;if(error){console.error('AGENDA ADMIN:',error);grid.innerHTML='<p class="muted">Não foi possível carregar a agenda.</p>';return}const rows=data||[],ids=[...new Set(rows.map(x=>x.user_id).filter(Boolean))];let cm={};if(ids.length){const r=await sb.from('profiles').select('id,name,phone,email').in('id',ids);if(r.error)console.error('CLIENTES AGENDA:',r.error);else cm=Object.fromEntries((r.data||[]).map(x=>[x.id,x]))}grid.innerHTML=slots().map(t=>{const b=rows.find(x=>String(x.time).slice(0,5)===t);if(!b)return`<div class="agenda-row"><div class="agenda-time">${t}</div><div class="agenda-empty">Horário livre</div></div>`;const c=cm[b.user_id]||{};return`<div class="agenda-row"><div class="agenda-time">${t}</div><div class="agenda-booking"><b>${esc(c.name||'Cliente')}</b><span>${esc(serviceName(b.service_id))}</span><small>${esc(profName(b.professional_id))}</small><div class="agenda-actions"><button class="btn secondary" data-status-booking="${b.id}">Status</button><button class="btn secondary" data-cancel="${b.id}">Cancelar</button>${c.phone?`<button class="btn secondary" data-wa="${esc(c.phone)}" data-wa-name="${esc(c.name||'Cliente')}">WhatsApp</button>`:''}</div></div></div>`}).join('')}
	function initClientBooking(){const d=$('#clientDate');if(d){if(!d.value)d.value=today();d.min=today()}}
	async function loadClientTimes(){if(!isClient())return;const sid=$('#clientService')?.value,pid=$('#clientProfessional')?.value,date=$('#clientDate')?.value,grid=$('#clientTimeGrid');if(!grid)return;if(!sid||!pid||!date){grid.innerHTML='<p class="muted">Selecione serviço, profissional e data.</p>';$('#bookingSummary')?.classList.add('hidden');return}const {data,error}=await sb.from('bookings').select('id,time,service_id,status').eq('professional_id',pid).eq('date',date).neq('status','cancelled');if(error){console.error('HORÁRIOS:',error);grid.innerHTML='<p class="muted">Não foi possível consultar os horários.</p>';return}const dur=duration(sid),occ=data||[],available=slots().filter(t=>{const s=timeMin(t),e=s+dur;return !occ.some(b=>{const bs=timeMin(b.time),be=bs+duration(b.service_id);return s<be&&e>bs})});grid.innerHTML=available.length?available.map(t=>`<button type="button" class="time-option" data-booking-time="${t}">${t}</button>`).join(''):'<p class="muted">Não há horários disponíveis para esta data.</p>'}
		function atualizarResumoAgendamento(time){const sid=$('#clientService')?.value,pid=$('#clientProfessional')?.value,date=$('#clientDate')?.value;if(!sid||!pid||!date)return;$('#summaryService').textContent=serviceName(sid);$('#summaryProfessional').textContent=profName(pid);$('#summaryDate').textContent=fmtDate(date);$('#summaryTime').textContent=time;$('#bookingSummary')?.classList.remove('hidden');$('#bookingSummary').dataset.time=time;$$('.time-option').forEach(x=>x.classList.toggle('selected',x.dataset.bookingTime===time))}
		async function createBooking(){if(!isClient()){alert('Apenas clientes podem realizar este agendamento.');return}const sid=$('#clientService')?.value,pid=$('#clientProfessional')?.value,date=$('#clientDate')?.value,time=$('#bookingSummary')?.dataset.time;if(!sid||!pid||!date||!time){alert('Selecione serviço, profissional, data e horário.');return}const {data:a}=await sb.auth.getUser(),u=a?.user;if(!u){alert('Sua sessão expirou. Faça login novamente.');return}const {data:existing}=await sb.from('bookings').select('id').eq('user_id',u.id).eq('professional_id',pid).eq('date',date).eq('time',time).neq('status','cancelled').limit(1);if(existing?.length){alert('Você já possui um agendamento neste horário.');return}const {error}=await sb.from('bookings').insert({user_id:u.id,service_id:sid,professional_id:pid,date,time,status:'confirmed'});if(error){console.error('CRIAR AGENDAMENTO:',error);alert('Não foi possível realizar o agendamento.');return}alert('Agendamento realizado com sucesso.');$('#bookingSummary')?.classList.add('hidden');$('#bookingSummary')?.removeAttribute('data-time');await consultarAgenda()}
		async function consultarAgenda(){if(!isClient())return;const {data:a}=await sb.auth.getUser(),u=a?.user,list=$('#clientBookingsList');if(!list||!u)return;const {data,error}=await sb.from('bookings').select('*').eq('user_id',u.id).order('date').order('time');if(error){console.error('MINHA AGENDA:',error);list.innerHTML='<p class="muted">Não foi possível carregar seus agendamentos.</p>';return}if(!data?.length){list.innerHTML='<p class="muted">Você ainda não possui agendamentos.</p>';return}list.innerHTML=data.map(b=>`<div class="list-row"><div><b>${fmtDate(b.date)} às ${String(b.time).slice(0,5)}</b><small>${esc(serviceName(b.service_id))} • ${esc(profName(b.professional_id))}</small></div><div><span>${esc(b.status||'')}</span>${b.status!=='cancelled'?`<button class="btn secondary" data-client-cancel="${b.id}">Cancelar</button>`:''}</div></div>`).join('')}
		async function cancelarMeuAgendamento(id){if(!isClient())return;const {data:a}=await sb.auth.getUser(),u=a?.user;if(!u)return;const {error}=await sb.from('bookings').update({status:'cancelled'}).eq('id',id).eq('user_id',u.id);if(error){console.error('CANCELAR CLIENTE:',error);alert('Não foi possível cancelar o agendamento.');return}await consultarAgenda()}
		async function getClientRows(){if(!isAdmin())return[];const {data,error}=await sb.from('profiles').select('id,name,phone,email,birth,role').eq('role','client').order('name');if(error){console.error('CLIENTES:',error);return[]}return data||[]}
		async function loadClients(){if(!isAdmin())return;window.allClients=await getClientRows();renderClients()}
		function renderClients(rows=window.allClients||[]){if(!isAdmin())return;const box=$('#clientList');if(!box)return;const s=($('#clientSearch')?.value||'').toLowerCase();const data=rows.filter(c=>[c.name,c.phone,c.email].join(' ').toLowerCase().includes(s));box.innerHTML=data.length?`<table><thead><tr><th>Nome</th><th>WhatsApp</th><th>Nascimento</th><th>E-mail</th><th>Ações</th></tr></thead><tbody>${data.map(c=>`<tr><td>${esc(c.name||'Sem nome')}</td><td>${esc(c.phone||'')}</td><td>${c.birth?fmtDate(c.birth):''}</td><td>${esc(c.email||'')}</td><td><button class="btn secondary" data-client-edit="${c.id}">Editar</button> <button class="btn secondary" data-client-bookings="${c.id}">Agenda</button></td></tr>`).join('')}</tbody></table>`:'<p class="muted">Nenhum cliente encontrado.</p>'}
		async function editarCliente(id){if(!isAdmin())return;const c=(window.allClients||[]).find(x=>String(x.id)===String(id));if(!c)return;const name=prompt('Nome:',c.name||'');if(name===null)return;const phone=prompt('WhatsApp:',c.phone||'');if(phone===null)return;const birth=prompt('Nascimento (AAAA-MM-DD):',c.birth||'');if(birth===null)return;const {error}=await sb.from('profiles').update({name:name.trim(),phone:phone.trim(),birth:birth||null}).eq('id',id);if(error){console.error('EDITAR CLIENTE:',error);alert('Não foi possível atualizar o cliente.');return}await loadClients();await dashboard()}
		async function visualizarAgendamentosCliente(id){if(!isAdmin())return;const {data,error}=await sb.from('bookings').select('*').eq('user_id',id).order('date').order('time');if(error){console.error(error);alert('Não foi possível consultar a agenda.');return}alert(data?.length?data.map(b=>`${fmtDate(b.date)} ${String(b.time).slice(0,5)} — ${serviceName(b.service_id)} — ${b.status}`).join('\n'):'Este cliente não possui agendamentos.')}
		function renderServices(){if(!isAdmin())return;const box=$('#serviceList');if(!box)return;box.innerHTML=services.length?services.map(s=>`<div class="list-row"><div><b>${esc(s.name)}</b><small>${money(s.price)} • ${s.duration||30} min</small></div><div><button class="btn secondary" data-service-edit="${s.id}">Editar</button> <button class="btn secondary" data-service-toggle="${s.id}">${s.active===false?'Ativar':'Desativar'}</button></div></div>`).join(''):'<p class="muted">Nenhum serviço cadastrado.</p>'}
		async function editarServico(id){if(!isAdmin())return;const s=services.find(x=>String(x.id)===String(id));if(!s)return;const name=prompt('Nome:',s.name||'');if(name===null)return;const price=prompt('Preço:',s.price);if(price===null)return;const dur=prompt('Duração:',s.duration||30);if(dur===null)return;const {error}=await sb.from('services').update({name:name.trim(),price:Number(price),duration:Number(dur)}).eq('id',id);if(error){console.error(error);alert('Não foi possível editar o serviço.');return}await loadServices()}
		async function alternarServico(id){if(!isAdmin())return;const s=services.find(x=>String(x.id)===String(id));if(!s)return;const {error}=await sb.from('services').update({active:s.active===false}).eq('id',id);if(error){console.error(error);alert('Não foi possível alterar o serviço.');return}await loadServices()}
		async function loadStock(){if(!isAdmin())return;const {data,error}=await sb.from('inventory').select('*').order('name');if(error){console.error('ESTOQUE:',error);return}$('#stockList').innerHTML=data?.length?data.map(x=>`<div class="list-row"><div><b>${esc(x.name)}</b><small>Estoque mínimo: ${x.min_qty??1}</small></div><span>${x.qty??0}</span></div>`).join(''):'<p class="muted">Nenhum produto cadastrado.</p>'}
		async function loadFinance(){if(!isAdmin())return;const m=today().slice(0,7),{data,error}=await sb.from('cash_entries').select('*').gte('date',`${m}-01`).lte('date',`${m}-31`).order('date',{ascending:false});if(error){console.error('FINANCEIRO:',error);return}const rows=data||[],inc=rows.filter(x=>x.type==='income').reduce((a,x)=>a+Number(x.amount||0),0),exp=rows.filter(x=>x.type==='expense').reduce((a,x)=>a+Number(x.amount||0),0);if($('#sumIncome'))$('#sumIncome').textContent=money(inc);if($('#sumExpense'))$('#sumExpense').textContent=money(exp);if($('#sumBalance'))$('#sumBalance').textContent=money(inc-exp);if($('#financeList'))$('#financeList').innerHTML=rows.map(x=>`<div class="list-row"><div><b>${esc(x.description||'')}</b><small>${fmtDate(x.date)}</small></div><span>${money(x.amount)}</span></div>`).join('')}
		function renderTeam(){if(!isAdmin())return;const box=$('#teamList');if(!box)return;box.innerHTML=professionals.length?professionals.map(p=>`<div class="list-row"><div><b>${esc(p.name)}</b><small>${esc(p.phone||'')}</small></div></div>`).join(''):'<p class="muted">Nenhum profissional cadastrado.</p>'}
		async function loadSettingsPage(){if(!isAdmin())return;await loadSettings();if($('#setName'))$('#setName').value=settings.name||'';if($('#setWhatsapp'))$('#setWhatsapp').value=settings.whatsapp||'';if($('#setStart'))$('#setStart').value=String(settings.start_time||'').slice(0,5);if($('#setEnd'))$('#setEnd').value=String(settings.end_time||'').slice(0,5);if($('#setInterval'))$('#setInterval').value=String(settings.slot_interval||30);if($('#setLogoUrl'))$('#setLogoUrl').value=settings.logo_url||'';if($('#shareUrl'))$('#shareUrl').textContent=location.href}
		async function saveSettings(){if(!isAdmin())return;const p={name:$('#setName')?.value.trim()||'DNH BARBEARIA',whatsapp:digits($('#setWhatsapp')?.value||''),start_time:$('#setStart')?.value||'08:00',end_time:$('#setEnd')?.value||'18:00',slot_interval:Number($('#setInterval')?.value||30),logo_url:$('#setLogoUrl')?.value.trim()||'dnh-logo.png'};const {data:old}=await sb.from('settings').select('id').limit(1).maybeSingle();const r=old?.id?await sb.from('settings').update(p).eq('id',old.id):await sb.from('settings').insert(p);if(r.error){console.error('CONFIG SALVAR:',r.error);alert('Não foi possível salvar as configurações.');return}settings={...settings,...p};alert('Configurações salvas.');await loadSettingsPage()}
		function setupAuth(){ $$('[data-auth]').forEach(b=>b.onclick=()=>{ $$('[data-auth]').forEach(x=>x.classList.remove('active'));b.classList.add('active');const login=b.dataset.auth==='login';$('#loginForm')?.classList.toggle('hidden',!login);$('#signupForm')?.classList.toggle('hidden',login)});$('#loginForm')?.addEventListener('submit',async e=>{e.preventDefault();const {error}=await sb.auth.signInWithPassword({email:$('#loginEmail').value.trim(),password:$('#loginPassword').value});if(error){console.error('ERRO DE LOGIN:',error);alert('E-mail ou senha incorretos.')}});$('#signupForm')?.addEventListener('submit',async e=>{e.preventDefault();const name=$('#signupName').value.trim(),phone=$('#signupPhone').value.trim(),birth=$('#signupBirth').value||null,email=$('#signupEmail').value.trim(),password=$('#signupPassword').value;const {data,error}=await sb.auth.signUp({email,password,options:{data:{name,phone,birth}}});if(error){console.error('CADASTRO:',error);alert(error.message||'Não foi possível criar a conta.');return}if(data.session&&data.user){const r=await sb.from('profiles').upsert({id:data.user.id,email,name,phone,birth,role:'client',active:true},{onConflict:'id'});if(r.error)console.error('PERFIL CADASTRO:',r.error)}alert(data.session?'Conta criada com sucesso.':'Conta criada. Confirme o e-mail antes de entrar.');});$('#logoutBtn')?.addEventListener('click',()=>sb.auth.signOut());$('#shareBtn')?.addEventListener('click',async()=>{const url=location.href;if(navigator.share){try{await navigator.share({title:settings.name,text:'Agende seu horário na DNH Barbearia',url})}catch(e){if(e.name!=='AbortError')console.error(e)}}else{await navigator.clipboard?.writeText(url);alert('Link copiado.')}});$('#copyShare')?.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(location.href);alert('Link copiado.')}catch{prompt('Copie o link:',location.href)}})}
		
		async function openAdminBookingModal(){
		if(!isAdmin())return;
		await Promise.all([loadServices(),loadProfessionals(),loadClients()]);
		const clients=window.allClients||[];
		if(!clients.length){alert('Nenhum cliente cadastrado. Cadastre o cliente antes de agendar.');return}
		document.getElementById('adminBookingModal')?.remove();
		const modal=document.createElement('div');
		modal.id='adminBookingModal';
		modal.style.cssText='position:fixed;inset:0;background:rgba(0,0,0,.78);z-index:9999;display:flex;align-items:center;justify-content:center;padding:20px;';
		modal.innerHTML=`<div style="background:#111;border:1px solid #444;border-radius:16px;width:min(560px,100%);max-height:90vh;overflow:auto;padding:22px;box-shadow:0 20px 60px rgba(0,0,0,.5)">
			<div style="display:flex;justify-content:space-between;align-items:center;gap:12px;margin-bottom:18px"><div><span class="eyebrow">ADMINISTRADOR</span><h2 style="margin:4px 0">Novo agendamento</h2><p class="muted" style="margin:0">Agende para qualquer cliente cadastrado.</p></div><button type="button" id="closeAdminBooking" class="btn secondary">Fechar</button></div>
			<label>Cliente<select id="adminBookClient"><option value="">Selecione um cliente</option>${clients.map(c=>`<option value="${esc(c.id)}">${esc(c.name||c.email||'Cliente')} — ${esc(c.phone||c.email||'')}</option>`).join('')}</select></label>
			<label>Serviço<select id="adminBookService"><option value="">Selecione um serviço</option>${services.filter(x=>x.active!==false).map(x=>`<option value="${esc(x.id)}">${esc(x.name)} — ${money(x.price)} (${x.duration||30} min)</option>`).join('')}</select></label>
			<label>Profissional<select id="adminBookProfessional"><option value="">Selecione um profissional</option>${professionals.filter(x=>x.active!==false).map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join('')}</select></label>
			<label>Data<input id="adminBookDate" type="date" value="${today()}" min="${today()}"></label>
			<div style="margin-top:14px"><label>Horário</label><div id="adminBookTimes" class="time-grid"><p class="muted">Selecione cliente, serviço, profissional e data.</p></div></div>
			<button type="button" id="adminBookConfirm" class="btn gold full" disabled style="margin-top:18px">Confirmar agendamento</button>
		</div>`;
		document.body.appendChild(modal);
		const close=()=>modal.remove();
		$('#closeAdminBooking')?.addEventListener('click',close);
		modal.addEventListener('click',e=>{if(e.target===modal)close()});
		const refresh=()=>loadAdminBookingTimes();
		$('#adminBookService')?.addEventListener('change',refresh);
		$('#adminBookProfessional')?.addEventListener('change',refresh);
		$('#adminBookDate')?.addEventListener('change',refresh);
		await loadAdminBookingTimes();
		$('#adminBookConfirm')?.addEventListener('click',async()=>{
		const btn=$('#adminBookConfirm'),clientId=$('#adminBookClient')?.value,sid=$('#adminBookService')?.value,pid=$('#adminBookProfessional')?.value,date=$('#adminBookDate')?.value,time=btn?.dataset.time;
		if(!clientId||!sid||!pid||!date||!time){alert('Selecione cliente, serviço, profissional, data e horário.');return}
		btn.disabled=true;btn.textContent='Agendando...';
		const {error}=await sb.from('bookings').insert({user_id:clientId,service_id:sid,professional_id:pid,date,time,status:'confirmed'});
		if(error){console.error('ADMIN CRIAR AGENDAMENTO:',error);alert(`Não foi possível realizar o agendamento.\n${error.message||''}`);btn.disabled=false;btn.textContent='Confirmar agendamento';return}
		alert('Agendamento realizado com sucesso.');
		close();
		await agendaAdmin();
		await dashboard();
		});
		}
		async function loadAdminBookingTimes(){
		const grid=$('#adminBookTimes'),btn=$('#adminBookConfirm');
		if(!grid||!btn)return;
		const sid=$('#adminBookService')?.value,pid=$('#adminBookProfessional')?.value,date=$('#adminBookDate')?.value;
		btn.disabled=true;delete btn.dataset.time;
		if(!sid||!pid||!date){grid.innerHTML='<p class="muted">Selecione serviço, profissional e data.</p>';return}
		const {data,error}=await sb.from('bookings').select('id,time,service_id,status').eq('professional_id',pid).eq('date',date).neq('status','cancelled');
		if(error){console.error('HORÁRIOS ADMIN:',error);grid.innerHTML=`<p class="muted">Não foi possível consultar os horários.<br>${esc(error.message||'')}</p>`;return}
		const dur=duration(sid),occ=data||[];
		const available=slots().filter(t=>{const start=timeMin(t),end=start+dur;return !occ.some(b=>{const bs=timeMin(b.time),be=bs+duration(b.service_id);return start<be&&end>bs})});
			grid.innerHTML=available.length?available.map(t=>`<button type="button" class="time-option" data-admin-time="${t}">${t}</button>`).join(''):'<p class="muted">Não há horários disponíveis para esta data.</p>';
			$$('#adminBookTimes [data-admin-time]').forEach(x=>x.addEventListener('click',()=>{ $$('#adminBookTimes [data-admin-time]').forEach(y=>y.classList.remove('selected'));x.classList.add('selected');btn.dataset.time=x.dataset.adminTime;btn.disabled=false; }));
			}
			
			function setupForms(){setupAuth();$('#clientService')?.addEventListener('change',loadClientTimes);$('#clientProfessional')?.addEventListener('change',loadClientTimes);$('#clientDate')?.addEventListener('change',loadClientTimes);$('#confirmBooking')?.addEventListener('click',async()=>{const b=$('#confirmBooking');b.disabled=true;b.textContent='Agendando...';try{await createBooking()}finally{b.disabled=false;b.textContent='Confirmar agendamento'}});$('#refreshClientBookings')?.addEventListener('click',consultarAgenda);$('#clientSearch')?.addEventListener('input',()=>renderClients());$('#birthdayOnly')?.addEventListener('click',()=>{if(!isAdmin())return;const m=today().slice(5,7);renderClients((window.allClients||[]).filter(x=>x.birth&&String(x.birth).slice(5,7)===m))});$('#refreshAgenda')?.addEventListener('click',agendaAdmin);$('#saveSettings')?.addEventListener('click',saveSettings);$('#serviceForm')?.addEventListener('submit',async e=>{e.preventDefault();if(!isAdmin())return;const {error}=await sb.from('services').insert({name:$('#serviceName').value.trim(),price:Number($('#servicePrice').value),duration:Number($('#serviceDuration').value),active:true});if(error){console.error(error);alert('Não foi possível cadastrar o serviço.');return}e.target.reset();await loadServices()});$('#stockForm')?.addEventListener('submit',async e=>{e.preventDefault();if(!isAdmin())return;const {error}=await sb.from('inventory').insert({name:$('#stockName').value.trim(),qty:Number($('#stockQty').value),min_qty:Number($('#stockMin').value)});if(error){console.error(error);alert('Não foi possível cadastrar o produto.');return}e.target.reset();await loadStock()});$('#financeForm')?.addEventListener('submit',async e=>{e.preventDefault();if(!isAdmin())return;const {error}=await sb.from('cash_entries').insert({type:$('#financeType').value,description:$('#financeDesc').value.trim(),amount:Number($('#financeAmount').value),date:$('#financeDate').value||today()});if(error){console.error(error);alert('Não foi possível registrar o lançamento.');return}e.target.reset();$('#financeDate').value=today();await loadFinance();await dashboard()});$('#teamForm')?.addEventListener('submit',async e=>{e.preventDefault();if(!isAdmin())return;const {error}=await sb.from('professionals').insert({name:$('#teamName').value.trim(),phone:$('#teamPhone').value.trim(),active:true});if(error){console.error(error);alert('Não foi possível cadastrar o profissional.');return}e.target.reset();await loadProfessionals()})}
			document.addEventListener('click',async e=>{const x=e.target.closest('[data-page]');if(x){e.preventDefault();await go(x.dataset.page);return}let b=e.target.closest('[data-booking-time]');if(b&&isClient()){atualizarResumoAgendamento(b.dataset.bookingTime);return}b=e.target.closest('[data-client-cancel]');if(b&&isClient()){if(confirm('Cancelar este agendamento?'))await cancelarMeuAgendamento(b.dataset.clientCancel);return}b=e.target.closest('[data-client-edit]');if(b&&isAdmin()){await editarCliente(b.dataset.clientEdit);return}b=e.target.closest('[data-client-bookings]');if(b&&isAdmin()){await visualizarAgendamentosCliente(b.dataset.clientBookings);return}b=e.target.closest('[data-service-edit]');if(b&&isAdmin()){await editarServico(b.dataset.serviceEdit);return}b=e.target.closest('[data-service-toggle]');if(b&&isAdmin()){await alternarServico(b.dataset.serviceToggle);return}b=e.target.closest('[data-admin-new-booking]');if(b&&isAdmin()){await openAdminBookingModal();return}b=e.target.closest('[data-cancel]');if(b&&isAdmin()){if(!confirm('Cancelar este agendamento?'))return;const r=await sb.from('bookings').update({status:'cancelled'}).eq('id',b.dataset.cancel);if(r.error){console.error(r.error);alert('Não foi possível cancelar.')}else await agendaAdmin();return}b=e.target.closest('[data-status-booking]');if(b&&isAdmin()){const status=prompt('Status: confirmed, completed ou cancelled','completed');if(!status)return;const r=await sb.from('bookings').update({status}).eq('id',b.dataset.statusBooking);if(r.error){console.error(r.error);alert('Não foi possível atualizar o status.')}else await agendaAdmin();return}b=e.target.closest('[data-wa]');if(b&&isAdmin()){const phone=digits(b.dataset.wa);if(phone)window.open(`https://wa.me/${phone}?text=${encodeURIComponent(`Olá ${b.dataset.waName||'Cliente'}! Aqui é da DNH Barbearia. Estamos entrando em contato sobre seu agendamento.`)}`,'_blank')}});
			async function handleLoggedIn(){if(!await user()){await sb.auth.signOut();return}$('#authView')?.classList.add('hidden');$('#appView')?.classList.remove('hidden');aplicarPermissoesUI();await loadSettings();await loadServices();await loadProfessionals();if(isAdmin())await go('dashboard');else await go('agenda')}
			function handleLoggedOut(){$authReset();profile=null;$('#appView')?.classList.add('hidden');$('#authView')?.classList.remove('hidden');}
			function $authReset(){ $$('.page').forEach(x=>x.classList.remove('active')); }
			async function boot(){if(!cfg.supabaseUrl||!cfg.supabaseAnonKey){$('#configNotice')?.classList.remove('hidden');return}setupForms();if($('#agendaDate'))$('#agendaDate').value=today();if($('#financeDate'))$('#financeDate').value=today();const {data}=await sb.auth.getSession();if(data.session)await handleLoggedIn();sb.auth.onAuthStateChange((event,session)=>{setTimeout(()=>{if(session)handleLoggedIn().catch(console.error);else handleLoggedOut()},0)})}
			boot();
